name: GitHub Script
author: GitHub
description: Run simple scripts using the GitHub client
branding:
  color: blue
  icon: code
inputs:
  script:
    description: The script to run
    required: true
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  debug:
    description: Whether to tell the GitHub client to log details of its requests
    default: false
  user-agent:
    description: An optional user-agent string
    default: actions/github-script
  previews:
    description: A comma-separated list of API previews to accept
  result-encoding:
    description: Either "string" or "json" (default "json")—how the result will be encoded
    default: json
  retries:
    description: "The number of times to retry a request"
    default: "0"
  retry-after:
    description: "The number of seconds between retries"
    default: "0"
  do-not-retry:
    description: "A comma separated list of status codes that will NOT be retried. Example: '400,500'"
    default: ""
outputs:
  result:
    description: The return value of the script, stringified with `JSON.stringify`
runs:
  using: node16
  main: dist/index.js
