on:
  push: {branches: master}

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - id: output-set
        uses: actions/github-script@master
        with:
          script: return core.getInput('input-value')
          result-encoding: string
          input-value: output
      - run: |
          if [[ "${{steps.output-set.outputs.result}}" != "output" ]]; then
            exit 1
          fi
