on:
  push: {branches: master}

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - id: output-set
        uses: actions/github-script@master
        with:
          script: return 'test'
          result-encoding: string
      - run: |
          if [[ "${{steps.output-set.outputs.result}}" != "test" ]]; then
            exit 1
          fi
